version: '3.3'

services:
  postgres:
    image: 'postgres:15.1-alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db