spring.datasource:
  url: ${SPRING_DATASOURCE_URL}
  username: ${SPRING_DATASOURCE_USERNAME}
  password: ${SPRING_DATASOURCE_PASSWORD}
  driver-class-name: org.postgresql.Driver

# Hibernate props
spring.jpa:
  hibernate.ddl-auto: validate
  properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
        type: trace
        stat: debug