-- liquibase formatted sql

-- changeset belov:1702061831775-1
CREATE TABLE run
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    last_modified_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    avg_speed        FLOAT4,
    distance         BIGINT,
    finish_date_time TIMESTAMP WITH TIME ZONE,
    finish_latitude  FLOAT4,
    finish_longitude FLOAT4,
    start_date_time  TIMESTAMP WITH TIME ZONE                NOT NULL,
    start_latitude   FLOAT4                                  NOT NULL,
    start_longitude  FLOAT4                                  NOT NULL,
    user_id          BIGINT                                  NOT NULL,
    CONSTRAINT "runPK" PRIMARY KEY (id)
);

-- changeset belov:1702061831775-2
CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    last_modified_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    birth_date       TIMESTAMP WITH TIME ZONE                NOT NULL,
    first_name       VARCHAR(255)                            NOT NULL,
    gender           VARCHAR(255)                            NOT NULL,
    last_name        VARCHAR(255)                            NOT NULL,
    CONSTRAINT "usersPK" PRIMARY KEY (id)
);

-- changeset belov:1702061831775-3
CREATE INDEX run_user_id_i ON run (user_id);

-- changeset belov:1702061831775-4
ALTER TABLE run
    ADD CONSTRAINT run_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id);

